server:
    port: 80
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
    undertow:
        io-threads: 4
        worker-threads: 10
        buffer-size: 16384
        accesslog:
            enabled: true
            dir: /home/jcala/blog/log/server_log
            pattern: combined
logging:
    config: classpath:logback-spring.xml
    path: /home/jcala/blog/log/spring_log
spring:
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB
    cache:
        cache-names: ehcache
        ehcache:
            config: ehcache.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/jcala_blog?useUnicode:true&amp;characterEncoding:UTF-8
        driverClassName: com.mysql.jdbc.Driver
        schema: classpath:import.sql
        data: classpath:data.sql
        initialize: false
        sql-script-encoding: UTF-8
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 50
            minimum-idle: 5
