server:
  port: 8080
  compression:
     min-response-size: 1
     enabled: true
  undertow:
     accesslog:
       enabled: true
       dir: arget/logs
       pattern: combined
logging:
  config: classpath:logback-spring.xml
spring:
  velocity:
    cache: false
    view-names: about,blogs,error,index,login,projects,tags,archives,admin/mkEditor
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8
    properties.directive.parse.max.depth: 10

