server:
  port: 8080
  compression:
     min-response-size: 1
     enabled: true
  undertow:
     accesslog:
       enabled: true
       dir: arget/logs
       pattern: combined
logging:
  config: classpath:logback-spring.xml
  path: /Users/jcala/logs
  level: info
spring:
  velocity:
    cache: true
    view-names: about,blogs,error,index,login,projects,tags,archives
